test

diff --git a/kur1 b/kur1
--- a/kur1
+++ b/kur1
@@ -1,7 +1,7 @@
 #!/bin/sh
 kurulum()
 {
-
+partitioning="true"
 debug=false
 DISK=${installdisk/*\//}
  #########################################################
@@ -24,56 +24,114 @@ fallback(){
             exit 1
         fi
 }
-ldconfig
+if [[ $UID -eq 0 ]] ; then
+    mount -t devtmpfs devtmpfs /dev || true
+    mount -t proc proc /proc || true
+    mount -t sysfs sysfs /sys || true
+    mount -t efivarfs efivars /sys/firmware/efi/efivars || true
+fi
+
 mkdir -p hedef
 mkdir -p kaynak
 mkdir -p cdrom
-
-echo "*********************disk bölümleri silindi ******************************"
-    
-  dd if=/dev/zero of=/dev/${DISK} bs=512 count=1
-    sync && sleep 1
-   
-        yes | parted /dev/${DISK} mktable msdos || fallback
-        #yes | parted /dev/${DISK} mkpart primary fat32 1 "1024MB" || fallback
-        yes | parted /dev/${DISK} mkpart primary fat32 1 "100%" || fallback
-        sync && sleep 1
-         yes |e2fsck -f /dev/${DISK}1
-         sync && sleep 1
-	yes |tune2fs -O ^metadata_csum /dev/${DISK}1
-	 sync && sleep 1
-        yes | mkfs.ext2  /dev/${DISKX}1 || fallback
-        yes | parted /dev/${DISK} set 1 esp on || fallback
-        sync && sleep 1
-        mount /dev/${DISKX}1  /hedef || fallback
-        mkdir -p /hedef/boot 
-echo "********************* kurulum başladı******************************"
-if [[ ! -f /run/live/rootfs/filesystem.squashfs ]] ; then
+if [[ ! -d /run/live/rootfs/filesystem.squashfs ]] ; then
 mount -t iso9660 -o loop /dev/sr0 cdrom
 mount -t squashfs -o loop /cdrom/live/filesystem.squashfs /kaynak
 else
 mount /dev/loop0 /kaynak || true
 fi
+
+echo "*********************disk bölümleri silindi ******************************"
+#--------------------------------------------------------------------------------------------
+if [[ "$partitioning" == "true" ]] ; then
+    dd if=/dev/zero of=/dev/${DISK} bs=512 count=1
+    sync && sleep 1
+    
+     if [[ -d /sys/firmware/efi ]] ; then
+        yes | parted /dev/${DISK} mktable gpt || fallback
+        yes | parted /dev/${DISK} mkpart primary fat32 1 "100MB" || fallback
+        yes | parted /dev/${DISK} mkpart primary fat32 100MB "100%" || fallback
+        sync && sleep 1
+        yes | mkfs.vfat /dev/${DISKX}1 || fallback
+        sync && sleep 1
+        yes | mkfs.ext4  /dev/${DISKX}2 || fallback
+        yes | parted /dev/${DISK} set 1 esp on || fallback
+        sync && sleep 1
+        mount /dev/${DISKX}2  /hedef || fallback
+        mkdir -p /hedef/boot/efi || true
+        mount /dev/${DISKX}1 /hedef/boot/efi  || fallback
+    else
+        yes | parted /dev/${DISK} mktable msdos || fallback
+        yes | parted /dev/${DISK} mkpart primary fat32 1 "100%" || fallback
+        sync && sleep 1
+        yes |e2fsck -f /dev/${DISK}1
+        sync && sleep 1
+	yes |tune2fs -O ^metadata_csum /dev/${DISK}1
+	sync && sleep 1
+        yes | mkfs.ext4  /dev/${DISKX}1 || fallback
+        yes | parted /dev/${DISK} set 1 esp on || fallback
+        sync && sleep 1
+        mount /dev/${DISKX}1  /hedef || fallback
+        mkdir -p /hedef/boot
+    fi
+else
+    echo "Please input rootfs part (example sda2)"
+    read rootfs
+    echo "Please input mbr (example sda)"
+    read DISK
+    mount /dev/$rootfs /hedef
+    if [[ -d /sys/firmware/efi ]] ; then
+        echo "Please input efi part (example sda1)"
+        read efifs
+        mkdir -p /hedef/boot/efi
+        mount /dev/$efifs /hedef/boot/efi
+    fi
+fi
+ 
+#-------------------------------------------------------------------------------------------------
+echo "********************* kurulum başladı******************************"
 #cp -prfv /kaynak/* /hedef/
 #rsync -axHAWXS --numeric-ids --info=progress2 /kaynak/ /hedef/
+
+#*************************************************************************************
+echo -e "\033[31mSistem yuklenmeye baslandi. Tahmini 3-5 dakika sürecektir.. Lutfen bekleyiniz.....\033[0m"
+#echo "Sistem yuklenmeye baslandi. Tahmini 3-5 dakika sürecektir..Lutfen bekleyiniz....."
+#echo "........................................................................................................."
+echo -e "\033[32m...............................................................................................\033[0m"
 ls /kaynak/ | xargs -n1 -P$(nproc) -I% /usr/bin/rsync -ravhHAX --info=progress2 /kaynak/% /hedef/ &>/dev/null|| fallback
-cp /cdrom/boot/initrd.img /hedef/boot/initrd.img-$(uname -r)
-cp /cdrom/boot/vmlinuz /hedef/boot/vmlinuz-$(uname -r)
+#rsync -ravhHAX --info=progress2 /kaynak/% /hedef/|| fallback
+echo -e "\033[32m...............................................................................................\033[0m"
+echo -e "\033[31mSistem yuklenmesi tamamlaniyor....\033[0m"
+echo -e "\033[32m...............................................................................................\033[0m"
+echo -e "\033[31mSon ayarlar tamamlaniyor....\033[0m"
+#*************************************************************************************
+cp /run/live/medium/boot/initrd.img /hedef/boot/initrd.img-$(uname -r)
+cp /run/live/medium/boot/vmlinuz /hedef/boot/vmlinuz-$(uname -r)
 cp /hedef/etc/kernel-config /hedef/boot/config-$(uname -r)
 sync
 
-mkdir -p /hedef/dev
-mkdir -p /hedef/sys
-mkdir -p /hedef/proc
-mkdir -p /hedef/run
-mkdir -p /hedef/tmp
-sync
+if [[ "$partitioning" == "true" ]] ; then
+    if [[ -d /sys/firmware/efi ]] ; then
+        echo "/dev/${DISKX}2 /               ext4    errors=remount-ro        0       1" > /hedef/etc/fstab  || fallback
+        echo "/dev/${DISKX}1 /boot/efi       vfat    umask=0077               0       0" >> /hedef/etc/fstab  || fallback
+    else
+        echo "/dev/${DISKX}1 /               ext4    errors=remount-ro        0       1" > /hedef/etc/fstab  || fallback
+    fi
+else
+    echo "Please write fstab file. Press any key to open editor."
+    read -n 1 -s
+    nano /hedef/etc/fstab
+fi
 
-mount --bind /dev /hedef/dev
-mount --bind /sys /hedef/sys
-mount --bind /proc /hedef/proc
-mount --bind /run /hedef/run
-mount --bind /tmp /hedef/tmp
+for i in dev sys proc run 
+do
+    mkdir -p /hedef/$i || true 
+    mount --bind /$i /hedef/$i  || fallback
+done
+if [[ -d /sys/firmware/efi ]] ; then
+    mount --bind /sys/firmware/efi/efivars /hedef/sys/firmware/efi/efivars || fallback
+fi
+
 chroot /hedef /bin/busybox --install -s /bin
 
 cp /hedef/etc/skel/.xinitrc /hedef/root/
@@ -82,7 +140,13 @@ cp /hedef/etc/skel/.profile /hedef/root/
 
 
 chroot /hedef /usr/sbin/update-initramfs -u -k $(uname -r)
-chroot /hedef grub-install --removable --boot-directory=/boot /dev/${DISK} --target=i386-pc
+#chroot /hedef grub-install --removable --boot-directory=/boot /dev/${DISK} --hedef=i386-pc
+if [[ -d /sys/firmware/efi ]] ; then
+    chroot /hedef mount -t efivarfs efivarfs /sys/firmware/efi/efivars || true
+    chroot /hedef grub-install /dev/${DISK} --hedef=x86_64-efi || fallback
+else
+    chroot /hedef grub-install /dev/${DISK} --hedef=i386-pc || fallback
+fi
 
 mkdir -p /hedef/boot/grub
 bid=$(blkid /dev/${DISK}1|cut -d' ' -f2|cut -c 7-42)
